urls:
  - biomarkers-30600-both_sexes-irnt
  - biomarkers-30610-both_sexes-irnt
  - biomarkers-30620-both_sexes-irnt
  - biomarkers-30630-both_sexes-irnt
  - biomarkers-30640-both_sexes-irnt
  - biomarkers-30670-both_sexes-irnt
  - biomarkers-30680-both_sexes-irnt
  - biomarkers-30690-both_sexes-irnt
  - biomarkers-30700-both_sexes-irnt
  - biomarkers-30710-both_sexes-irnt
  - biomarkers-30720-both_sexes-irnt
  - biomarkers-30730-both_sexes-irnt
  - biomarkers-30750-both_sexes-irnt
  - biomarkers-30760-both_sexes-irnt
  - biomarkers-30770-both_sexes-irnt
  - biomarkers-30780-both_sexes-irnt
  - biomarkers-30810-both_sexes-irnt
  - biomarkers-30830-both_sexes-irnt
  - biomarkers-30860-both_sexes-irnt
  - biomarkers-30870-both_sexes-irnt
  - biomarkers-30890-both_sexes-irnt
  - categorical-120-both_sexes-1
  - categorical-1210-both_sexes-1210
  - categorical-1418-both_sexes-1
  - categorical-1428-both_sexes-0
  - categorical-1468-both_sexes-4
  - categorical-1538-both_sexes-2
  - categorical-1677-both_sexes-1677
  - categorical-1707-both_sexes-1
  - categorical-1747-both_sexes-4
  - categorical-1950-both_sexes-1950
  - categorical-20002-both_sexes-1226
  - categorical-20003-both_sexes-1140874420
  - categorical-20003-both_sexes-1140879802
  - categorical-20003-both_sexes-1140881856
  - categorical-20003-both_sexes-1140923346
  - categorical-20004-both_sexes-1477
  - categorical-20004-both_sexes-1479
  - categorical-20004-both_sexes-1480
  - categorical-20004-both_sexes-1483
  - categorical-20107-both_sexes-101
  - categorical-20107-both_sexes-9
  - categorical-20110-both_sexes-100
  - categorical-20111-both_sexes-1
  - categorical-20111-both_sexes-101
  - categorical-20116-both_sexes-1
  - categorical-20117-both_sexes-2
  - categorical-2040-both_sexes-2040
  - categorical-2207-both_sexes-2207
  - categorical-2257-both_sexes-2257
  - categorical-3571-both_sexes-3571
  - categorical-3606-both_sexes-3606
  - categorical-4293-both_sexes-3
  - categorical-5001-both_sexes-5001
  - categorical-6138-both_sexes-5
  - categorical-6138-both_sexes-6
  - categorical-6142-both_sexes-6
  - categorical-6144-both_sexes-5
  - categorical-6149-both_sexes-3
  - categorical-6149-both_sexes-6
  - categorical-6151-both_sexes-7
  - categorical-6154-both_sexes-3
  - categorical-6155-both_sexes-100
  - categorical-6160-both_sexes-4
  - categorical-6162-both_sexes-1
  - categorical-6164-both_sexes-2
  - categorical-6164-both_sexes-5
  - continuous-1050-both_sexes
  - continuous-1110-both_sexes
  - continuous-1120-both_sexes
  - continuous-1140-both_sexes
  - continuous-1160-both_sexes
  - continuous-1180-both_sexes
  - continuous-1239-both_sexes
  - continuous-1249-both_sexes
  - continuous-1259-both_sexes
  - continuous-1289-both_sexes
  - continuous-1299-both_sexes
  - continuous-1329-both_sexes
  - continuous-1339-both_sexes
  - continuous-1349-both_sexes
  - continuous-135-both_sexes
  - continuous-1408-both_sexes
  - continuous-1478-both_sexes
  - continuous-1498-both_sexes
  - continuous-1548-both_sexes
  - continuous-1588-both_sexes
  - continuous-1697-both_sexes
  - continuous-1717-both_sexes
  - continuous-1757-both_sexes
  - continuous-20010-both_sexes-irnt
  - continuous-20022-both_sexes-irnt
  - continuous-20409-both_sexes
  - continuous-20485-both_sexes
  - continuous-20498-both_sexes
  - continuous-20508-both_sexes
  - continuous-20515-both_sexes
  - continuous-20519-both_sexes
  - continuous-20520-both_sexes
  - continuous-2178-both_sexes
  - continuous-2217-both_sexes-irnt
  - continuous-2237-both_sexes
  - continuous-2267-both_sexes
  - continuous-2277-both_sexes
  - continuous-30040-both_sexes-irnt
  - continuous-30060-both_sexes-irnt
  - continuous-30100-both_sexes-irnt
  - continuous-30150-both_sexes-irnt
  - continuous-30180-both_sexes-irnt
  - continuous-30190-both_sexes-irnt
  - continuous-30280-both_sexes-irnt
  - continuous-30520-both_sexes-irnt
  - continuous-3148-both_sexes-irnt
  - continuous-398-both_sexes
  - continuous-400-both_sexes-irnt
  - continuous-4125-both_sexes-irnt
  - continuous-4195-both_sexes-irnt
  - continuous-5096-both_sexes-irnt
  - continuous-5116-both_sexes-irnt
  - continuous-5257-both_sexes-irnt
  - continuous-709-both_sexes
  - continuous-728-both_sexes
  - continuous-738-both_sexes
  - continuous-816-both_sexes
  - continuous-845-both_sexes
  - continuous-864-both_sexes
  - continuous-874-both_sexes-irnt
  - continuous-904-both_sexes
  - continuous-924-both_sexes
  - continuous-943-both_sexes
  - continuous-LDLC-both_sexes-medadj_irnt
  - continuous-MAP-both_sexes-manual_raw
  - continuous-NAP-both_sexes-irnt
  - icd10-M16-both_sexes
  - icd10-M17-both_sexes
  - icd10-R19-both_sexes
  - phecode-317-both_sexes
  - phecode-327-both_sexes
  - phecode-459-both_sexes
  - phecode-550
  - phecode-550
  - phecode-574
  - phecode-594-both_sexes
  - phecode-714-both_sexes
  - phecode-760-both_sexes
  - phecode-960-both_sexes
  - prescriptions-GABA_agonist|sedative-both_sexes
  - prescriptions-amoxicillin_clavulanic_acid-both_sexes
  - prescriptions-biguanides|diabetes-both_sexes
  - prescriptions-latanoprost-both_sexes
